# * Version resolution
"""Resolve the application version for display in the UI.

A frozen (PyInstaller) build cannot run git, so the version is baked in at
build time as ``bank_analyzer/_version.py`` (generated by CI: the bare semver
on a release tag, the short commit hash for any other build).  When running
from a source checkout that generated file is absent, so fall back to the live
git short hash.  If even that fails, return ``None`` so the UI layer can show a
translatable placeholder instead of hardcoding user-facing text here.
"""

import importlib
import subprocess
from pathlib import Path

# * Public API

def get_version() -> str | None:
    baked_version = _read_baked_version()
    if baked_version is not None:
        return baked_version
    git_version = _read_git_short_hash()
    if git_version is not None:
        return git_version
    return None

# * Helpers

def _read_baked_version() -> str | None:
    try:
        version_module = importlib.import_module('bank_analyzer._version')
    except ImportError:
        return None
    return getattr(version_module, 'VERSION', None)

def _read_git_short_hash() -> str | None:
    repo_dir = Path(__file__).resolve().parent.parent
    try:
        result = subprocess.run(
            ['git', 'rev-parse', '--short', 'HEAD'],
            cwd=repo_dir,
            capture_output=True,
            text=True,
            check=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return None
    short_hash = result.stdout.strip()
    return short_hash
